In [17]:
#Question 1
print("""
A python library is a collection of pre written code used for specific functionalities
      """)


A python library is a collection of pre written code used for specific functionalities
      


In [18]:
#Question 2
print("""
-NumPy arrays are more memory-efficient and faster than Python lists.
-All elements in a NumPy array must be of the same data type     
-Since all elements are of the same type, NumPy arrays use less memory
      """)


-NumPy arrays are more memory-efficient and faster than Python lists.
-All elements in a NumPy array must be of the same data type     
-Since all elements are of the same type, NumPy arrays use less memory
      


In [19]:
#Question 3
import numpy as np
a = np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
print(a.shape)
print(a.size)
print(a.ndim)

(3, 4)
12
2


In [20]:
#Question 4
b = np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
b[0]

array([1, 2, 3, 4])

In [25]:
#Question 5
b[2,3]

12

In [32]:
#Question 6
odd_index = b.flatten()[1::2]
odd_index

array([ 2,  4,  6,  8, 10, 12])

In [36]:
#Question 7
import numpy as np
random_matrix = np.random.rand(3, 3)
print(random_matrix)



[[0.40443026 0.65899415 0.98400444]
 [0.12574156 0.39270109 0.62820458]
 [0.01503889 0.03801564 0.37148793]]


In [37]:
#Question 8
print("""
np.random.rand: Generates random numbers from a uniform distribution
np.random.randn: Generates random numbers from a standard normal distribution       
      """)


np.random.rand: Generates random numbers from a uniform distribution
np.random.randn: Generates random numbers from a standard normal distribution       
      


In [41]:
#Question 9
new_arr = np.expand_dims(b, axis=0)  
print(new_arr)
print(new_arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(1, 3, 4)


In [42]:
#Question 10
np.transpose(b)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [47]:
#Question 11
A = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
np.multiply(A,B)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [55]:
np.dot(A,B)
#Doesnt work here

In [56]:
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [57]:
B-A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
#Question 12
arr = np.array([1, 256, 65536], dtype=np.int16)
arr_swapped = arr.byteswap()
print("Original array:", arr)
print("Array with swapped byte order:", arr_swapped)

Original array: [  1 256   0]
Array with swapped byte order: [256   1   0]


C:\Users\arush\AppData\Local\Temp\ipykernel_17976\2101763161.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 65536 to int16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array([1, 256, 65536], dtype=np.int16)


In [65]:
#Question 13
print("""The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix. """)

The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix. 


In [66]:
#Question 14
print("""The np.reshape() function in NumPy is used to change the shape of an array without changing its data.""")

The np.reshape() function in NumPy is used to change the shape of an array without changing its data.


In [68]:
#Question 15
print("The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. ")

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. 
